version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: LetterBoxDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: LetterBoxDB      # <-- Updated database name
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql      # <-- persist database files here

volumes:
  mysql_data:                          # <-- named volume declared here
